# Generated by Django 4.1.5 on 2023-01-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=256)),
                ('slide', models.CharField(max_length=2048)),
            ],
        ),
    ]
