# Generated by Django 4.1.5 on 2023-01-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(verbose_name='順序')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Strongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abst', models.CharField(max_length=25, verbose_name='抽象')),
            ],
        ),
        migrations.CreateModel(
            name='Studystates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('will', '学習したい'), ('ing', '学習してる'), ('can', '使える')], max_length=16, verbose_name='学習状況')),
                ('language', models.CharField(max_length=32)),
                ('imgurl', models.URLField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='strong_exps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.CharField(max_length=50, verbose_name='説明')),
                ('strong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exps', to='index.strongs')),
            ],
        ),
    ]
