# Generated by Django 4.1.5 on 2023-01-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strongs',
            old_name='abst',
            new_name='strong',
        ),
    ]
