# Generated by Django 4.1.5 on 2023-01-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_strong_strongexp_delete_strong_exps_delete_strongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histories',
            new_name='History',
        ),
        migrations.RenameModel(
            old_name='Studystates',
            new_name='Studystate',
        ),
    ]
