# Generated by Django 4.1.5 on 2023-01-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_histories_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studystate',
            old_name='language',
            new_name='tech',
        ),
    ]
